apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  annotations:
    kubernetes.io/ingress.class: traefik
    #traefik.frontend.rule.type: PathPrefixStrip
    #traefik.ingress.kubernetes.io/rewrite-target: /cloud9
spec:
  rules:
  - host: "verdun.cocooning.tech"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: port-1
