apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}
  name: {{ .Chart.Name }}
spec:
  ports:
  - name: port-2
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: 8000
  selector:
    app: {{ .Release.Name }}
