apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: {{ .Chart.Name }}
        env:
        - name: "TZ"
          value: "Europe/Paris"
        - name: "PUID"
          value: "1000"
        - name: "PGID"
          value: "1000"
        volumeMounts:
        - mountPath: "/code"
          name: "vol1"
      volumes:
        - hostPath:
            path: "/apps"
            type: ""
          name: "vol1"
