apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}
  namespace: cocooning
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rewrite-target: /test
spec:
  rules:
  - host: "verdun.cocooning.tech"
    http:
      paths:
      - path:
        backend:
          serviceName: {{ .Chart.Name }}
          servicePort: {{ .Values.service.port }}
