apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud9
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
          - containerPort: {{ .Values.service.port }}
            hostPort: {{ .Values.service.port }}
            name: cloud9
            protocol: TCP
          env:
          - name: "PUID"
            value: "1000"
          - name: "PGID"
            value: "1000"
          - name: "TZ"
            value: "Europe/Paris"
          volumeMounts:
          - mountPath: "/code"
            name: "vol2"
      volumes:
        - hostPath:
            path: "/apps"
            type: ""
          name: "vol2"
      schedulerName: default-scheduler
