apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cloud9
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: verdun.cocooning.tech
    http:
      paths:
      - backend:
          serviceName: cloud9
          servicePort: 8000
        path: /cloud9
        pathType: ImplementationSpecific
