apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hassio
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: verdun.cocooning.tech
    http:
      paths:
      - backend:
          serviceName: hassio
          servicePort: 8000
        path: /hassio
        pathType: ImplementationSpecific
