apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: cocooning
  annotations:
    meta.helm.sh/release-namespace: cocooning
spec:
  ports:
  - name: port-1
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}
