apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  namespace: cocooning
spec:
  rules:
  - host: "verdun.cocooning.tech"
    http:
      paths:
      - path: /whoami
        backend:
          serviceName: {{ .Release.Name }}
          servicePort: {{ .Values.service.port }}
