replicaCount: 1
image:
  repository: "lspipepr/cloud9"
  # repository: "lsiobase/cloud9"
  # repository: "linuxserver/cloud9"
  tag: "go"
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8000
