apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: whoami
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: verdun.coconning.tech
    - http:
        paths:
        - path: /whoami
          pathType: Prefix
          backend:
            serviceName: whoami
            servicePort: 80
