apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    field.cattle.io/creatorId: user-hfxbj
    field.cattle.io/ingressState: '{"d2hvYW1pL3dob2FtaS1wLXNnaHBrL3ZlcmR1bi5jb2Nvb25pbmcudGVjaC8vd2hvYW1pL3dob2FtaQ==":""}'
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.1.71"],"port":80,"protocol":"HTTP","serviceName":"whoami-p-sghpk:whoami","ingressName":"whoami-p-sghpk:whoami","hostname":"verdun.cocooning.tech","path":"/whoami","allNodes":false}]'
  generation: 1
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
          f:field.cattle.io/ingressState: {}
          f:field.cattle.io/publicEndpoints: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
      f:spec:
        f:rules: {}
    manager: Go-http-client
    operation: Apply
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: traefik
    operation: Apply
  name: whoami
  namespace: whoami-p-sghpk
  resourceVersion: "77792"
  selfLink: /apis/extensions/v1beta1/namespaces/whoami-p-sghpk/ingresses/whoami
  uid: 06329d72-c551-4b30-8ab3-cbe61fa0a2ae
spec:
  rules:
  - host: verdun.cocooning.tech
    http:
      paths:
      - backend:
          serviceName: whoami
          servicePort: whoami
        path: /whoami
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 192.168.1.71
