apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
  namespace: {{ .Release.Name }}
  labels:
    io.cattle.field/appId: {{ .Release.Name }}
  managedFields:
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/creatorId: {}
          f:field.cattle.io/ingressState: {}
          f:field.cattle.io/publicEndpoints: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
      f:spec:
        f:rules: {}
    manager: Go-http-client
    operation: Update
  - apiVersion: extensions/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: traefik
    operation: Update
spec:
  rules:
  - host: verdun.cocooning.tech
    http:
      paths:
      - backend:
          serviceName: whoami
          servicePort: 80
        path: /whoami
        pathType: ImplementationSpecific
