apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: whoami
spec:
  rules:
  - host: verdun.cocooning.tech
    http:
      paths:
      - backend:
          servicePort: 80
        path: /whoami
        pathType: ImplementationSpecific
