apiVersion: v1
kind: Service
metadata:
  name: whoami
  namespace: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
  - name: default
    port: 42
    protocol: TCP
    targetPort: 42
  selector:
    workloadID_whoami: "true"
  sessionAffinity: None
  type: ClusterIP
