apiVersion: v1
kind: Service
metadata:
  name: whoami
  ownerReferences:
  - apiVersion: v1beta1/extensions
    controller: true
    kind: Ingress
    name: whoami
    uid: 2728c419-abef-497a-ae48-c487c1e94753
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    workloadID_ingress-whoami: "true"
