apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: https
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
