apiVersion: v1
kind: Service
metadata:
  name: whoami
  labels:
    cattle.io/creator: norman
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
  selector:
    workloadID_ingress-whoami: "true"
