apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: '["deployment:whoami-p-sghpk:whoami"]'
  name: whoami
  namespace: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
  - name: default
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workloadID_whoami: "true"
  sessionAffinity: None
  type: ClusterIP
