apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/ipAddresses: "null"
    field.cattle.io/targetDnsRecordIds: "null"
    field.cattle.io/targetWorkloadIds: '["deployment:whoami-p-sghpk:whoami"]'
  name: whoami
  namespace: {{ .Release.Name }}
spec:
  clusterIP: None
  ports:
  - name: whoami
    port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.port }}
  selector:
    workloadID_whoami: "true"
  sessionAffinity: None
  type: {{ .Values.service.type }}
