apiVersion: v1
kind: Service
metadata:
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:default:workloadwhoami"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
  creationTimestamp: "2020-06-22T08:02:59Z"
  labels:
    cattle.io/creator: norman
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:field.cattle.io/targetWorkloadIds: {}
          f:workload.cattle.io/targetWorkloadIdNoop: {}
          f:workload.cattle.io/workloadPortBased: {}
        f:labels:
          .: {}
          f:cattle.io/creator: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"a3324833-2f1f-4f92-84e8-9ae51e62ea09"}:
            .: {}
            f:apiVersion: {}
            f:controller: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        f:clusterIP: {}
        f:ports: {}
        f:selector:
          .: {}
          f:workload.user.cattle.io/workloadselector: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: Go-http-client
    operation: Apply
    time: "2020-06-22T08:02:59Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:ports:
          k:{"port":80,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
    manager: Mozilla
    operation: Apply
    time: "2020-06-22T08:08:05Z"
  name: workloadwhoami
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1beta2
    controller: true
    kind: deployment
    name: workloadwhoami
    uid: a3324833-2f1f-4f92-84e8-9ae51e62ea09
  resourceVersion: "102819"
  selfLink: /api/v1/namespaces/default/services/workloadwhoami
  uid: 3489d420-dd91-4b0f-83ae-0444c5633fa5
spec:
  clusterIP: None
  ports:
  - name: default
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    workload.user.cattle.io/workloadselector: deployment-default-workloadwhoami
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
