apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvctheia
spec:
  accessModes:
  - ReadWriteMany
  - ReadWriteOnce
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: managed-nfs-storage
  volumeName: pvtheia
